### ISSUE TITLE
按照你的一模一样照搬，最后提示调用失败

### ISSUE THREAD

**Issue by zivencn** [zyh94946/wx-msg-push-tencent#1]
按照你的一模一样照搬，最后提示调用失败

**Comment by zyh94946** [comment]
贴下云函数调用日志看看

**Comment by zivencn** [comment]
START RequestId:7962423c19d323a0014b3bae11e3453b

2021/03/27 23:58:06 event: map[headerParameters:map[] headers:map[accept:*/* accept-charset:utf-8; accept-encoding:gzip content-length:0 content-type:application/x-www-form-urlencoded endpoint-timeout:15 host:service-4mp4eyn6-1251422564.hk.apigw.tencentcs.com requestsource:APIGW user-agent:Go-http-client/1.1 x-api-requestid:7962423c19d323a0014b3bae11e3453b x-api-scheme:http x-b3-traceid:7962423c19d323a0014b3bae11e3453b x-qualifier:$DEFAULT] httpMethod:POST isBase64Encoded:false path:/msg_push/111 pathParameters:map[SECRET:111] queryString:map[] queryStringParameters:map[] requestContext:map[httpMethod:ANY identity:map[] path:/msg_push/{SECRET} serviceId:service-4mp4eyn6 sourceIp:9.70.159.228 stage:debug]]

2021/03/27 23:58:06 request: {POST map[]  map[SECRET:111]} json error: <nil>

2021/03/27 23:58:06 Request check fail 

ERROR RequestId:7962423c19d323a0014b3bae11e3453b Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"invoke function failed with err: {\"Message\":\"Request check fail \",\"Type\":\"errorString\",\"StackTrace\":null,\"ShouldExit\":false}","statusCode":430}

END RequestId:7962423c19d323a0014b3bae11e3453b

Report RequestId:7962423c19d323a0014b3bae11e3453b Duration:1ms Memory:128MB MemUsage:19.136719MB

**Comment by zivencn** [comment]
START RequestId:cfe8085a5ea1d95d24de8e83c5307892

2021/03/27 22:52:20 event: map[headerParameters:map[] headers:map[accept-encoding:gzip content-type:application/x-www-form-urlencoded endpoint-timeout:15 host:service-4mp4eyn6-1251422564.hk.apigw.tencentcs.com:443 requestsource:APIGW user-agent:Go-http-client/1.1 x-api-requestid:cfe8085a5ea1d95d24de8e83c5307892 x-api-scheme:https x-b3-traceid:cfe8085a5ea1d95d24de8e83c5307892 x-qualifier:$DEFAULT] httpMethod:GET isBase64Encoded:false path:/msg_push/CORP_SECRET pathParameters:map[SECRET:CORP_SECRET] queryString:map[content:消息内容 title:消息标题] queryStringParameters:map[] requestContext:map[httpMethod:ANY identity:map[] path:/msg_push/{SECRET} serviceId:service-4mp4eyn6 sourceIp:123.207.136.134 stage:release]]

2021/03/27 22:52:20 request: {GET map[content:消息内容 title:消息标题]  map[SECRET:CORP_SECRET]} json error: <nil>

2021/03/27 22:52:20 Request check fail 

ERROR RequestId:cfe8085a5ea1d95d24de8e83c5307892 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"invoke function failed with err: {\"Message\":\"Request check fail \",\"Type\":\"errorString\",\"StackTrace\":null,\"ShouldExit\":false}","statusCode":430}

END RequestId:cfe8085a5ea1d95d24de8e83c5307892

Report RequestId:cfe8085a5ea1d95d24de8e83c5307892 Duration:1ms Memory:128MB MemUsage:19.183594MB

**Comment by zyh94946** [comment]
调用示例中 `https://你的Api网关域名/你的云函数名称/CORP_SECRET?title=消息标题&content=消息内容`
CORP_SECRET 这个地方要换成你云函数环境变量`CORP_SECRET`的值

**Comment by zivencn** [comment]
找到问题了，是环境变量里的值在复制过去的时候，前面有了空格，谢谢哦

**Comment by zyh94946** [comment]
客气
