### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by superen7527** [zyh94946/wx-msg-push-tencent#2]
不好意思打扰一下。。实在不想打扰。。不过我不是这方面的。。只是手里有一个腾讯云服务器刚好也需要这方面才找到你这里。。。。
就是云函数我记得超过一定会收费 这个有办法在轻量云服务器上直接用吗，如果觉得问题太那啥了直接close吧 打扰了

**Comment by zyh94946** [comment]
稍微改下就可以了，这一两天我抽空弄一个独立部署的版本吧。

**Comment by superen7527** [comment]
好的，十分感谢！！

**Comment by zyh94946** [comment]
> 不好意思打扰一下。。实在不想打扰。。不过我不是这方面的。。只是手里有一个腾讯云服务器刚好也需要这方面才找到你这里。。。。
> 就是云函数我记得超过一定会收费 这个有办法在轻量云服务器上直接用吗，如果觉得问题太那啥了直接close吧 打扰了

独立部署见 [wx-msg-push](https://github.com/zyh94946/wx-msg-push)
