### ISSUE TITLE
重复内容无法收到

### ISSUE THREAD

**Issue by superen7527** [zyh94946/wx-msg-push-tencent#3]
EnableDuplicateCheck 已经是0 时间间隔也调到0了 重复内容还是不能及时推送 是哪里还需要设置问题吗

**Comment by zyh94946** [comment]
这个你手动改完需要重新编译，不知道你是否忘记了？后续会考虑放到环境变量里，就省的编译了。

**Comment by superen7527** [comment]
嗯嗯，好，谢啦。

**Comment by superen7527** [comment]
不好意思老哥再叨扰下 发现消息是默认全部应用用户都会接收
   "touser" : "UserID1|UserID2|UserID3",
   "toparty" : "PartyID1|PartyID2",
   "totag" : "TagID1 | TagID2",
企业微信api是具有这些选择用户推送的 能不能在api网址上支持 不用全部 支持touser就好了 类似&touser=UserID1|UserID2|UserID3这种写法 没有写就还是默认全部
因为我在做一个家庭控制组 父母不太会用wifi 我就利用来回通知的形式触发安卓条件来开关检查网络 如果能支持就方便很多了 如果不方便就算了没事的  我再想想其他办法 谢谢。

**Comment by zyh94946** [comment]
> 不好意思老哥再叨扰下 发现消息是默认全部应用用户都会接收
> "touser" : "UserID1|UserID2|UserID3",
> "toparty" : "PartyID1|PartyID2",
> "totag" : "TagID1 | TagID2",
> 企业微信api是具有这些选择用户推送的 能不能在api网址上支持 不用全部 支持touser就好了 类似&touser=UserID1|UserID2|UserID3这种写法 没有写就还是默认全部
> 因为我在做一个家庭控制组 父母不太会用wifi 我就利用来回通知的形式触发安卓条件来开关检查网络 如果能支持就方便很多了 如果不方便就算了没事的 我再想想其他办法 谢谢。

新版本支持了
