### ISSUE TITLE
多个应用id

### ISSUE THREAD

**Issue by superen7527** [zyh94946/wx-msg-push-tencent#4]
如果需要开启多个应用 可以在高级配置里面支持设置  CORP_ID2   CORP_SECRET3 这样的形式吗 不然只能新建新函数 新api 要额外收费

**Comment by zyh94946** [comment]
多应用的问题下次更新会考虑

**Comment by superen7527** [comment]
谢谢！麻烦啦！可以给个二维码我稍微捐赠下嘛

**Comment by zyh94946** [comment]
> 谢谢！麻烦啦！可以给个二维码我稍微捐赠下嘛

感谢你的支持，赞赏时可留下你微信，可以添加沟通。
<img src="https://user-images.githubusercontent.com/1629896/116341617-d5d0ad80-a813-11eb-8a9d-8670d57b4f11.png" width="50%" />

**Comment by superen7527** [comment]
学生党..第一次捐赠不知道多少合适...一顿饭钱，感觉对于你来说是不是少了...我都不好意思加微信了 就不加微信打扰了 全当支持吧...
只是弄了好几天 你这个是我唯一能实现类似Server酱自己的api的搭建教程 我是个门外汉.. 看到会支持服务器部署就很激动 捐赠点略表心意。。别嫌弃就好

**Comment by zyh94946** [comment]
> 学生党..第一次捐赠不知道多少合适...一顿饭钱，感觉对于你来说是不是少了...我都不好意思加微信了 就不加微信打扰了 全当支持吧...
> 只是弄了好几天 你这个是我唯一能实现类似Server酱自己的api的搭建教程 我是个门外汉.. 看到会支持服务器部署就很激动 捐赠点略表心意。。别嫌弃就好

不会不会，感谢你的支持。能够帮到别人我也很开心。

**Comment by zyh94946** [comment]
> 如果需要开启多个应用 可以在高级配置里面支持设置 CORP_ID2 CORP_SECRET3 这样的形式吗 不然只能新建新函数 新api 要额外收费

多应用独立部署版支持了，云函数的暂时还不支持。
