### ISSUE TITLE
vercel的免费云函数支持golang，有考虑移植一下么？

### ISSUE THREAD

**Issue by xxJogger** [zyh94946/wx-msg-push-tencent#5]
如题，vercel官方介绍如下。
![IMG_20210512_144409](https://user-images.githubusercontent.com/10105226/117930433-8f5d7180-b330-11eb-8e7e-16afaac61316.jpg)

**Comment by zyh94946** [comment]
最近比较忙，暂时没有时间。有空再看吧

**Comment by xxJogger** [comment]
感谢大大，我也只是刚好想起来Vercel也能跑云函数。
